DROP TABLE IF EXISTS Staffs CASCADE;
DROP TABLE IF EXISTS Teams CASCADE;
DROP TABLE IF EXISTS Redeems CASCADE;

CREATE TABLE IF NOT EXISTS Teams (
    team_name TEXT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS Staffs (
    staff_pass_id TEXT PRIMARY KEY,
    team_name TEXT NOT NULL REFERENCES Teams,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS Redeems (
    redeem_id TEXT PRIMARY KEY,
    team_name TEXT NOT NULL REFERENCES Teams,
    redeemed_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(team_name)
);

-- Teams Data
INSERT INTO Teams VALUES ('BASS');
INSERT INTO Teams VALUES ('RUST');

-- Staff Data
INSERT INTO Staffs VALUES ('STAFF_H123804820G', 'BASS');
INSERT INTO Staffs VALUES ('MANAGER_T999888420B', 'RUST');
INSERT INTO Staffs VALUES ('BOSS_T000000001P', 'RUST');
